---

- name: wireguard | genkey | private key
  command: wg genkey
  register: wg_priv

- name: wireguard | genkey | set wg_privkey
  set_fact:
    wg_privkey: "{{ wg_priv.stdout }}"
    cacheable: yes

- name: wireguard | genkey | public key
  command: wg pubkey
  args:
    stdin: "{{ wg_privkey }}"
  register: wg_pub

- name: wireguard | genkey | set wg_pubkey
  set_fact:
    wg_pubkey: "{{ wg_pub.stdout }}"
    cacheable: yes

- name: wireguard | genkey | host_vars dir
  local_action:
    module: file
    path: "{{ wg_keydir }}/{{ inventory_hostname }}"
    state: directory

- name: wireguard | genkey | save keys in host_vars
  local_action:
    module: template
    src: wg.yml.j2
    dest: "{{ wg_keydir }}/{{ inventory_hostname }}/wg.yml"
