---

- name: wireguard | add repo
  tags:
  - apt
  apt_repository:
    repo: "deb {{ wg_repo }} {{ wg_repo_rel }} main"
    filename: wireguard

- name: wireguard | install packages
  tags:
  - package
  package:
    name:
      - "linux-headers-{{ ansible_kernel | regex_replace('^linux-headers-') }}"
      - bc
      - wireguard
  notify: restart networkd
