---

- import_tasks: install.yml

- include_tasks: genkey.yml
  tags:
  - genkey
  when: wg_privkey is not defined

- name: wireguard | systemd-networkd config
  tags:
  - config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/network/{{ wg_name }}.{{ item }}"
    mode: 0640
    group: systemd-network
  loop:
    - netdev
    - network
  notify: restart networkd
