---

- name: wireguard | install packages
  tags:
  - package
  package:
    name:
    - bc
    - wireguard
  notify: restart networkd

- include_tasks: genkey.yml
  when: wg_privkey is not defined

- name: wireguard | firewall config dir
  file:
    path: "{{ wg_iptables_conf | dirname }}"
    state: directory

- name: wireguard | systemd-networkd config
  tags:
  - config
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dst }}"
    mode: "{{ item.mode | d(omit) }}"
    group: systemd-network
  loop:
  - src: netdev
    dst: "/etc/systemd/network/{{ wg_name }}.netdev"
    mode: '0640'
  - src: network
    dst: "/etc/systemd/network/{{ wg_name }}.network"
  - src: iptables.conf
    dst: "{{ wg_iptables_conf }}"
  notify:
  - daemon-reload
  - restart networkd
  - restart resolved

