---

- name: "wireguard | add repo {{ wg_repo_rel }}"
  tags:
  - apt
  apt_repository:
    repo: "deb {{ wg_repo }} {{ wg_repo_rel }} main"
    filename: wireguard

- name: wireguard | install packages
  tags:
  - package
  package:
    name:
      - "linux-headers-{{ ansible_kernel }}"
      - bc
      - wireguard
  notify: restart networkd

- include_tasks: genkey.yml
  when: wg_privkey is not defined

- name: wireguard | systemd-networkd drop-in dir
  file:
    path: "{{ wg_dropin | dirname }}"
    state: directory

- name: wireguard | systemd-networkd config
  tags:
    - config
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dst }}"
    mode: "{{ item.mode | d(0644) }}"
    owner: root
    group: systemd-network
  loop:
    - src: netdev
      dst: "/etc/systemd/network/{{ wg_name }}.netdev"
      mode: '0640'
    - src: network
      dst: "/etc/systemd/network/{{ wg_name }}.network"
    - src: systemd-networkd.conf
      dst: "{{ wg_dropin }}"
  notify:
    - daemon-reload
    - restart networkd
    - restart resolved

