#! /usr/bin/env ansible-playbook
# Configure wireguard VPN
# Replace 'wg' with your own inventory group
---
- name: wireguard | VPN nodes
  hosts: wg
  roles:
  - role: wireguard
    when: 
    - ansible_virtualization_type != 'openvz'
    - ansible_virtualization_type != 'container'

