#! /usr/bin/env ansible-playbook
# Uninstall wireguard VPN
# Use '-l' option to specify hosts from which to uninstall
---
- name: wireguard | uninstall
  hosts: all
  tasks:
  - include_role:
      name: wireguard
      tasks_from: uninstall.yml
