#! /usr/bin/env ansible-playbook
# Uninstall wireguard VPN
# Run prior to removing host from inventory groups, so hostvars are accessible
---
- name: wireguard | uninstall
  hosts: wg
  tasks:
  - include_role:
      name: wireguard
      tasks_from: uninstall.yml
