#! /usr/bin/env ansible-playbook
# Uninstall wireguard VPN
# Replace 'wg' with your own inventory group
---
- name: wireguard | uninstall
  hosts: wg
  tasks:
    - include_role:
        name: wireguard
        tasks_from: uninstall.yml
